config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: :show
  root to: "pages#home"
  get "profile", to: "pages#profile"
  get "calendar", to: "pages#calendar"
  resources :certifications, only: [:index,:new, :create, :destroy]
  resources :listings, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, :reviews, only: [:index, :new, :create, :show]
  end
  resources :bookings, :reviews, only: [:destroy]
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :user
  has_one_attached :photo

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model
    pg_search_scope :search_by_category,
    against: [ :category ],
    associated_against: {
      user: [ :fullname ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index
    @listings = Listing.all
    @markers = @listings.geocoded.map do |listing|
      {
        lat: listing.latitude,
        lng: listing.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { listing: listing }),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def show
    @listing = Listing.find(params[:id])
    @booking = Booking.new
    @users = User.all
    @reviews = @listing.reviews
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_params)
    if @listing.save
      redirect_to listing_path(@listing)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to listings_path(@listing.list), status: :see_other
  end

  private

  def listing_params
    params.require(:listing).permit(:category, :location, :details, :user_id, :photo)
  end
end

app/views/listings/index.html.erb
<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/listings/new.html.erb
<% if user_signed_in? %>

<div class="listing-form">

<div class="form-container">

  <div class="d-flex justify-content-center align-items-center">
    <div class="text-center w-50">
      <div class="create-list-container p-4 rounded shadow">
        <h1 class="listing-heading">Create a New Listing</h1>
        <%= simple_form_for [@listing] do |f| %>
          <div class="listing-form-group">
              <%= f.input :category,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "category" },
                          wrapper_html: { class: 'col-sm-12' },
                          label_html: { class: 'listing-paragraph col-sm-2 control-label' } %>
          </div>
          <div class="listing-form-group">
              <%= f.input :location,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "location" },
                          wrapper_html: { class: 'col-sm-12' },
                          label_html: { class: 'listing-paragraph col-sm-2 control-label' } %>
          </div>
          <div class="listing-form-group">
              <%= f.input :details,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "details" },
                          wrapper_html: { class: 'col-sm-12' },
                          label_html: { class: 'listing-paragraph col-sm-2 control-label' } %>
          </div>
          <%= f.input :photo, as: :file %>
            <%= f.submit "Create Listing", class: "btn btn-outline-light shadow-sm mt-3" %>
          <% end %>
      </div>
    </div>
  </div>
</div>
<% else %>

  <%= render 'shared/log_in_prompt' %>

<% end %>

app/views/listings/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dcy2dfahw/image/upload/v1695299259/victor-freitas-WvDYdXDzkhs-unsplash_mqvxo5.jpg);">
</div>

<div class="listing-show-container">
  <% if user_signed_in? %>
    <div class="listing-container">
          <% if @listing.photo.present? %>
          <%= cl_image_tag @listing.photo.key, height: 300, width: 400, crop: :fill %>
          <% else %>
          <%= image_tag "https://res.cloudinary.com/dcy2dfahw/image/upload/v1695044898/dumbbell_l3d5ls.png", class:"profile-photo" %>
          <% end %>
          <%= link_to user_path(@listing.user) do %>
            <h1 class="listing-heading"><%= @fullname = @listing.user.fullname.titleize %></h1>
          <% end %>
        <h3 class="listing-sub-heading"><%= @listing.category %></h3>
        <h4 class="listing-paragraph"><%= @listing.location %></h4>
        <p class="listing-paragraph"><%= @listing.details %></p>
    </div>
  </div>
</div>
<br>
<br>
<div class="reviews">
    <div class="listing-show-links">
    <h4 class="listing-sub-heading">Reviews</h4>
    <ul class="list-group m-4">
    <% @reviews.each do |review| %>
      <div class="review">
        <li class="review-group-item"><%= review.content %></li>
        <div class="d-flex justify-content-center align-items-center">
          <div class="review-group-item">
            <p>Rating:</p>
            <div class="star <%= 'filled' if review.rating >= 1 %>"></div>
            <div class="star <%= 'filled' if review.rating >= 2 %>"></div>
            <div class="star <%= 'filled' if review.rating >= 3 %>"></div>
            <div class="star <%= 'filled' if review.rating >= 4 %>"></div>
            <div class="star <%= 'filled' if review.rating >= 5 %>"></div>
          </div>
        </div>
      </div>
    <% end %>
  </ul>
  </div>
</div>

  <div class="listing-show-links">
      <%= link_to "Make a Booking", new_listing_booking_path(@listing, @booking), class: "btn btn-outline-light" %>
    </div>
    <div class="listing-show-links">
      <br>
      <%= link_to "Back to Home", root_path, class: "btn btn-outline-light" %>
  </div>
  <% else %>
  <%= render 'shared/log_in_prompt' %>
  <% end %>