config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: :show
  root to: "pages#home"
  get "profile", to: "pages#profile"
  get "calendar", to: "pages#calendar"
  resources :certifications, only: [:index,:new, :create, :destroy]
  resources :listings, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, :reviews, only: [:index, :new, :create, :show]
  end
  resources :bookings, :reviews, only: [:destroy]
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :listing
  belongs_to :user

  validates :start_time, presence: true
  validates :end_time, presence: true

  default_scope -> { order(:start_time) }

  def time
    "#{start_time.strftime('%I:%M %p')} - #{end_time.strftime('%I:%M %p')}"
  end

  def multi_days?
    (end_time.to_date - start_time.to_date).to_i >= 1
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
    @listing = Listing.find(params[:listing_id])
    @review = Review.new
  end

  def new
    @booking = Booking.new
    @listing = Listing.find(params[:listing_id])
    # Calendar date display option below (monthly view)
    start_date = params.fetch(:start_date, Date.today).to_date
    @bookings = Booking.where(start_time:
      start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
  end

  def create
    @listing = Listing.find(params[:listing_id])
    @booking = current_user.bookings.new(booking_params)
    @booking.listing = @listing
    if @booking.save!
      redirect_to listing_booking_path(@listing, @booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to listing_booking_path(@booking), status: :see_other
  end

  def load_partial
    partial_name = params[:name]

    if partial_name == "client_view"
      render partial: "client_view", locals: { booking: @bookings }
    elsif partial_name == "trainer_view"
      render partial: "trainer_view", locals: { booking: @bookings }
    else
      render plain: "Invalid partial name", status: :bad_request
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :comment, :listing_id, :user_id)
  end
end

app/views/bookings/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dcy2dfahw/image/upload/v1695305448/josh-nuttall-uNQ-TTg_qNY-unsplash_twes8f.jpg);">
</div>
<% if user_signed_in? %>

  <div class="homepage-container">
    <h1 class="homepage-heading">Bookings</h1>
    <h2 class="listing-sub-heading">Manage you commitments</h2>
    <br>
    <div data-controller="toggle">
      <button data-action="click->toggle#fire" class="btn btn-outline-light" data-toggle-target="togglableElement">Upcoming sessions booked by me.</button>
      <br>
      <div data-toggle-target="togglableClientView">
        <div class="listings-row">
          <% @bookings.each do |booking| %>
            <% user = User.find(booking.user_id) %>
            <% trainer = User.find(booking.listing.user_id) %>
            <% if user.id == current_user.id %>
              <div class="listing">
                <p>Booking Date: <%= booking.date %></p>
                <p>Trainer: <%= trainer.fullname.titleize %></p>
                <p><%= booking.listing.category %></p>
                <p><%= booking.listing.details %></p>
                <%= link_to 'Cancel', booking_path(booking),
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                  class: 'btn btn-secondary' %>
                <%= link_to 'View', listing_booking_path(booking.listing, booking),
                  class: 'btn btn-secondary' %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>

      <div data-toggle-target="togglableTrainerView" class="d-none">
        <div class="listings-row">
          <% @bookings.each do |booking| %>
            <% trainer = User.find(booking.listing.user_id) %>
            <% user = User.find(booking.user_id) %>
            <% if trainer.id == current_user.id %>
              <div class="listing">
                <p>Booking Date: <%= booking.date %></p>
                <p>Client: <%= user.fullname.titleize %></p>
                <p><%= booking.listing.category %></p>
                <p><%= booking.listing.details %></p>
                <%= link_to 'Cancel', booking_path(booking),
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                  class: 'btn btn-secondary' %>
                <%= link_to 'View', listing_booking_path(booking.listing, booking),
                  class: 'btn btn-secondary' %>
              </div>
              <% end %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
<% else %>

  <%= render 'shared/log_in_prompt' %>

<% end %>

app/views/bookings/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dcy2dfahw/image/upload/v1695299256/karsten-winegeart-5sGYotxAuUA-unsplash_ushqkd.jpg);">
</div>

<% if user_signed_in? %>
<div class="booking-form-group">
  <div class="d-flex justify-content-center align-items-center">
    <div class="text-center w-50">
      <div class="bookings-container p-4 rounded shadow">
        <h1 class="listing-heading">Create a New Booking</h1>
        <br>
        <%= simple_form_for [@listing, @booking], html: { class: 'form', role: 'form' } do |f| %>
<!--          <div class="booking-form-group">
            <div class="col-sm-10">
              <%#= f.input :date,-->
<!--                          required: true,
                          autofocus: true,
                          input_html: { type: "date-local", autocomplete: "off" },
                          wrapper_html: { class: 'input-group' } %>
            </div>
          </div>-->
          <div class="booking-form-group">
            <div class="col-sm-10">
              <%= f.input :comment,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "comment" },
                          wrapper_html: { class: 'col-sm-12' } %>
            </div>
          </div>
          <div class="booking-form-group">
            <div class="col-sm-10">
              <%= f.input :start_time,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "start_time" },
                          wrapper_html: { class: 'col-sm-12' } %>
            </div>
          </div>
          <div class="booking-form-group">
            <div class="col-sm-10">
              <%= f.input :end_time,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "end_time" },
                          wrapper_html: { class: 'col-sm-12' } %>
            </div>
          </div>
          <%= f.submit "Create Booking", class: "btn btn-outline-light shadow-sm mt-3 mx-auto" %>
        <% end %>
      </div>
      <div class="calendar-container">
        <%= month_calendar(events: @bookings, end_attribute: :end_time) do |date, bookings| %>
          <%= date %>

          <% bookings.each do |booking| %>
            <div class="booking">
              <p><%= booking.name %></p>
              <small><%= booking.time unless booking.multi_days? %></small>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% else %>
  <%= render 'shared/log_in_prompt' %>
<% end %>

app/views/bookings/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dcy2dfahw/image/upload/v1695299257/jonathan-borba-lrQPTQs7nQQ-unsplash_uj6nt9.jpg);">
</div>
<% if user_signed_in? %>

  <div class="listing-show-container">
  <% @trainer = User.find(@booking.listing.user_id) %>
    <% @user = User.find(@booking.user_id) %>
      <h1 class="homepage-heading"><%= @trainer.fullname %></h1>

      <h2 class="listing-sub-heading"><%= @booking.date %></h2>

      <h3 class="listing-sub-heading"><%= @listing.category %></h3>


      <h3 class="listing-paragraph"><%= @booking.comment %></h3>
<h4 class="listing-sub-heading">Your Reviews</h4>
<ul class="list-group m-4">
  <% @listing.reviews.each do |review| %>
  <% if review.listing.user_id == current_user.id? %>
    <li class="list-group-item"><%= review.content %></li>
    <div class="d-flex justify-content-between align-items-center">
      <div>
        <p>Rating:</p>
        <div class="star <%= 'filled' if review.rating >= 1 %>"></div>
        <div class="star <%= 'filled' if review.rating >= 2 %>"></div>
        <div class="star <%= 'filled' if review.rating >= 3 %>"></div>
        <div class="star <%= 'filled' if review.rating >= 4 %>"></div>
        <div class="star <%= 'filled' if review.rating >= 5 %>"></div>
      </div>
      <div>
        <%= link_to "Delete",
          review_path(review),
          data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
          class: 'btn btn-danger btn-sm' %>
      </div>
    </div>
    <% end %>
  <% end %>
</ul>
<br>

<div class="m-4">
  <h2 class="listing-heading" >Add a Review</h2>
  <%= simple_form_for [@listing, @review] do |form| %>
    <%= form.input :content %>
    <%= form.input :rating, collection: [0, 1, 2, 3, 4, 5], label: "Select Rating" %>
    <%= form.submit 'Submit', class: "btn btn-outline-light" %>
  <% end %>
</div>


      <%= link_to "My Bookings", listing_bookings_path(@booking), class:"sub-heading" %>
  </div>

  <% else %>

    <%= render 'shared/log_in_prompt' %>

  <% end %>