config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: :show
  root to: "pages#home"
  get "profile", to: "pages#profile"
  get "calendar", to: "pages#calendar"
  resources :certifications, only: [:index,:new, :create, :destroy]
  resources :listings, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, :reviews, only: [:index, :new, :create, :show]
  end
  resources :bookings, :reviews, only: [:destroy]
end

app/views/pages/_info_window.html.erb
<p><%= listing.category %></p>
<p><%= listing.location %></p>

app/views/pages/_marker.html.erb
<div class="marker">
<%= image_tag "dumbbell-solid.svg", height: 30, width: 30, alt: "Logo"%>
</div>

app/views/pages/calendar.html.erb
Trainer Calendar Goes Here

app/views/pages/home.html.erb
<div class="homepage-container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dcy2dfahw/image/upload/v1695299257/sven-mieke-jO6vBWX9h9Y-unsplash_uipepe.jpg);">
  <div class="homepage-heading">
    <h1 class="homepage-heading">FlexBook</h1>
    <p class="homepage-paragraph">Your number one fitness service provider</p>
  </div>
  </div>
</div>
<div class="map-box-container">
  <div class="map", style="width: 80%; height: 300px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: root_path, method: :get, class: "d-flex", id: "search-form", data: { controller: "search", action: "submit->search#clearSearch" } do %>
      <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Type a keyword"
          %>
      <%= submit_tag "Search", name: "", class: "btn btn-outline-light" %>
    <% end %>
  </div>
</div>

  <div class="listings-row">
    <% @listings.each do |listing| %>
      <%= link_to listing_path(listing) do %>
        <div class="listing">
        <% @listing = Listing.find(listing.id) %>
          <% user = User.find(listing.user_id) %>
          <% if @listing.photo.present? %>
            <%= cl_image_tag @listing.photo.key, class:"profile-photo-smaller" %>
          <% else %>
            <%= image_tag "https://res.cloudinary.com/dcy2dfahw/image/upload/v1695044898/dumbbell_l3d5ls.png", class:"profile-photo-smaller" %>
          <% end %>
          <h4 class="listing-heading"><%= @fullname = user.fullname.titleize %></h4>
          <br>
          <div class="listing-sub-heading"><strong><%= listing.category %></strong></div>
          <br>
          <div class="listing-paragraph"><strong><%= listing.details %></strong></div>
          <br>
          <div class="listing-paragraph"><strong><%= listing.location %></strong></div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dcy2dfahw/image/upload/v1695299259/anastase-maragos-FP7cfYPPUKM-unsplash_j4vco8.jpg); background-position: center bottom;">
  <div class="homepage-heading">
    <h1 class="homepage-heading">My Profile</h1>
  </div>

</div>
<div class="profile-container">
  <div>
    <% if user_signed_in? %>
      <% if current_user.photo.present? %>
        <%= cl_image_tag current_user.photo.key, class:"profile-photo" %>
      <% else %>
      <div >
        <%= image_tag "https://res.cloudinary.com/dcy2dfahw/image/upload/v1695044898/dumbbell_l3d5ls.png", class:"profile-photo" %>
      </div>
      <% end %>
  </div>
  <div class="listing-show-container">
      <div>
        <h1 class="profile-heading" ><%= current_user.fullname %></h1>
      </div>
      <div>
        <div><h2><em><%= current_user.username %></em></h2>
        <% if current_user.certifications.present? %>
          <div><%= image_tag "https://res.cloudinary.com/dcy2dfahw/image/upload/v1695385959/png-transparent-verified-check-mark-confirmation-checkbox-passed-icon-removebg-preview_yrhnyr.png", class:"certified" %></div>
          <br>
        <% end %></div>
      </div>
      <p class="profile-paragraph">Gender: <%= current_user.gender %></p>
      <p class="profsile-paragraph">Age: <%= current_user.age %></p>
      <p class="profile-paragraph">Goal: <%= current_user.goal %></p>
      <p class="profile-paragraph">Fitness Level: <%= current_user.fitness_level %></p>
      <p class="profile-paragraph">Height: <%= current_user.height %></p>
      <p class="profile-paragraph">Weight: <%= current_user.weight %></p>
      <h3 class="profile-paragraph"><%= current_user.phone_number %></h3>

      <h3 class="profile-paragraph"><%= current_user.email %></h3>
      </div>
    </div>

      <div class="profile-links">

      <%= link_to "Certifications", certifications_path, class: "btn btn-outline-light" %>

      <%= link_to "My Training Calendar", calendar_path, class: "btn btn-outline-light" %>

      <%= link_to "Add New Listing", new_listing_path, class: "btn btn-outline-light" %>

      <%= link_to "My Bookings", listing_bookings_path(@listings), class: "btn btn-outline-light" %>
        <%= link_to edit_user_registration_path, class: "btn btn-outline-light" do %>
          Update Details
        <% end %>
      </div>
      </div>
    <% else %>
      <div>
        <%= render 'shared/log_in_prompt' %>
      </div>
    <% end %>

</div>