config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: :show
  root to: "pages#home"
  get "profile", to: "pages#profile"
  get "calendar", to: "pages#calendar"
  resources :certifications, only: [:index,:new, :create, :destroy]
  resources :listings, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, :reviews, only: [:index, :new, :create, :show]
  end
  resources :bookings, :reviews, only: [:destroy]
end

app/models/certification.rb
class Certification < ApplicationRecord
  validates :photo, presence: true
  belongs_to :user
  has_one_attached :photo
end

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController
  def index
    @certifications = current_user.certifications.all
  end

  def new
    @certification = Certification.new
  end

  def create
    @certification = current_user.certifications.new(certification_params)
    if @certification.save
      redirect_to certifications_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    @certification = Certification.find(params[:id])
    @certification.destroy
    redirect_to certifications_path, status: :see_other
  end

  private

  def certification_params
    params.require(:certification).permit(:photo)
  end
end

app/views/certifications/index.html.erb
<br>
<br>
<div class="listing-show-container">
  <% if @certifications.present? %>
    <div>
      <% @certifications.each do |certification| %>
        <% if certification.photo.present? %>
          <%= cl_image_tag certification.photo.key, height: 700, width: 450, crop: :fill %>
        <% end %>
                  <div>
                  <br>
          <%= link_to "Delete",
            certification_path(certification),
            data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
            class: 'btn btn-outline-light' %>
        </div>
        <br>
      <% end %>
</div>
<div class="listing-show-links" >
<%= link_to "Add certifications", new_certification_path, class: "btn btn-outline-light" %>
</div>
    </div>
  <% end %>

app/views/certifications/new.html.erb
<div class="certification-upload-form">
<%= simple_form_for(@certification) do |f| %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, "Submit Certification", class: 'btn btn-outline-light', data: { disable_with: 'Submitting' } %>
<% end %>
</div>